language: python

os:
    - linux

sudo: false

python:
    - 3.6
    - 3.7

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - MAIN_CMD='python setup.py'
        #- CONDA_CHANNELS='http://ssb.stsci.edu/astroconda'
        #- CONDA_DEPENDENCIES='pytest'
        - ASTROPY_GIT='git+https://github.com/astropy/astropy.git#egg=astropy'
        - TOOLS_GIT='git+https://github.com/spacetelescope/stsci.tools.git'
        - PIP_DEPENDENCIES="$TOOLS_GIT"

    matrix:
        - SETUP_CMD='egg_info'
        - SETUP_CMD='test'

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:
        # Numpy
        - python: 3.5
          env: NUMPY_VERSION=1.15 SETUP_CMD="test"

        # Numpy
        - python: 3.6
          env: NUMPY_VERSION=1.15 SETUP_CMD="test"

        # Do a PEP8 test with pycodestyle
        - python: 3.6
          env: MAIN_CMD='pycodestyle stwcs --count' SETUP_CMD=''

        # build sphinx documentation with warnings
        - python: 3.6
          env: MAIN_CMD="cd doc; make html"  SETUP_CMD=""
               PIP_DEPENDENCIES='sphinx-automodapi sphinx_rtd_theme'

        - python: 3.6
          env: NUMPY_VERSION=dev PIP_DEPENDENCIES="$ASTROPY_GIT SETUP_CMD='test'
               #EVENT_TYPE='cron'

        #- python: 3.6
        #  env: PIP_DEPENDENCIES="$ASTROPY_GIT SETUP_CMD='test'
               #EVENT_TYPE='cron'

        #- python: 3.7
        #  env: NUMPY_VERSION=dev SETUP_CMD='test'
               #EVENT_TYPE='cron'

        #- python: 3.7
        #  env: ASTROPY_VERSION=development SETUP_CMD='test'
               #EVENT_TYPE='cron'

    allow_failures:
        # Do a PEP8 test with pycodestyle
        - python: 3.6
          env: MAIN_CMD='pycodestyle stwcs --count' SETUP_CMD=''

install:
    #- git clone git://github.com/astropy/ci-helpers.git
    #- source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh
    pip install .[test]
script:
    - $MAIN_CMD $SETUP_CMD
